apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-pvc
  labels:
    app: html-deploy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi