apiVersion: v1
kind: Service
metadata:
  name: html-deploy
  labels:
    app: html-deploy
spec:
  ports:
    - port: 80
  selector:
    app: html-deploy
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deploy
  labels:
    app: html-deploy
spec:
  selector:
    matchLabels:
      app: html-deploy
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: html-deploy
        tier: frontend
    spec:
      containers:
      - image: abhijeetdebe/webserverimage:10
        name: html-deploy
        ports:
        - containerPort: 80
          name: html-deploy
        volumeMounts:
        - name: html-volume
          mountPath: /var/www/html/
      volumes:
      - name: html-volume
        persistentVolumeClaim:
          claimName: html-pvc
